databases:
  - name: rortest
    databaseName: rortest
    user: rortest
    region: frankfurt
    plan: free
services:
  - type: web
    name: nepremicninedb
    env: node
    buildCommand: "npm i --only=prod && npm run db:migrate:prod"
    startCommand: "npm run dev"
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rortest
          property: connectionString
